app/controllers/bidder/submissions_controller.rb
app/controllers/owner/tenders_controller.rb
config/routes.rb
test/controllers/bidder/submissions_controller_test.rb
test/controllers/owner/tenders_controller_test.rb

Completed routes, added new controllers, bidder and owner added.

routes controllers added

---

app/models/compatible_response.rb
app/models/prerequisite.rb
app/models/selected_prerequisite.rb
app/models/submission.rb
app/models/tender.rb
app/models/user.rb

validations partially complete

---

app/models/compatible_response.rb
app/models/prerequisite.rb
app/models/selected_prerequisite.rb
app/models/submission.rb
app/models/tender.rb
app/models/user.rb

validations updated

---

app/controllers/selected_prerequisites_controller.rb
app/views/selected_prerequisites/edit.html.erb

sprereq functional

---

app/controllers/tenders_controller.rb
app/views/tenders/show.html.erb

Tender Show Page Complete

---

app/controllers/tenders_controller.rb
app/models/selected_prerequisite.rb
app/models/tender.rb
app/views/tenders/_tender_form.html.erb
app/views/tenders/new.html.erb
config/routes.rb

added created route for tenders, got rid of description presence:true for selected_requisite, and created tender

Tenders can be created

---

app/controllers/selected_prerequisites_controller.rb
app/controllers/tenders_controller.rb
app/views/selected_prerequisites/edit.html.erb

Fixed selected_prerequisite link

selected_prerequisite fixed

---

app/controllers/tenders_controller.rb
app/views/tenders/_published.html.erb
app/views/tenders/show.html.erb

Completed show page, made if else statement and partials.

Completed show page if else

---

app/controllers/tenders_controller.rb
app/policies/tender_policy.rb
app/views/tenders/_form.html.erb
app/views/tenders/show.html.erb

Publish Button is now changing non-published tenders to publish tender

publish button working

---

app/controllers/submissions_controller.rb
app/policies/submission_policy.rb
app/views/submissions/index.html.erb
app/views/submissions/show.html.erb

Submissions Index Page logic is completed,  CSS left.

Index page logic done

---

app/views/shared/_navbar.html.erb

In Navbar, owners can only create tenders and contractors cannot create tenders.

Owners can only create tenders

---

app/views/shared/_navbar.html.erb

Update navbar image tag with .png

added .png to navbar image

---

app/assets/stylesheets/components/_card_pick.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_navbar_animation.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/views/owner/tenders/index.html.erb
app/views/pages/home.html.erb
app/views/selected_prerequisites/edit.html.erb
app/views/submissions/index.html.erb
app/views/tenders/_card.html.erb
app/views/tenders/_published.html.erb
app/views/tenders/show.html.erb

Navbar worked on, back buttons work for all current pages. Some CSS done for tenders page.

Navbar and all most pages button fixed

---

app/views/shared/_navbar.html.erb
app/views/submissions/index.html.erb
app/views/tenders/index.html.erb

Updated contractor tenders to have a cleaner view

updated contractor tenders view

---

app/controllers/submissions_controller.rb
app/javascript/controllers/index.js

Restored controllers/index.js, this fixed the log out btn.

Fixed log out btn

---

app/controllers/submissions_controller.rb
app/controllers/tenders_controller.rb
app/models/submission.rb
app/models/tender.rb
app/policies/submission_policy.rb
app/views/submissions/show.html.erb
app/views/tenders/show.html.erb

Completed contractor submission show for compatibility

Completed contractor submission show

---

app/views/submissions/show.html.erb

removed  <%= compatible_response.selected_prerequisite.description.body.to_plain_text %>
causing page to crash

fixed bug in submission compatibility

---

Gemfile
Gemfile.lock
app/controllers/bidder/submissions_controller.rb
app/models/submission.rb
app/views/bidder/submissions/index.html.erb

Added search bar to submission index page and working fine.

Seach bat for bidder completed

---

app/assets/stylesheets/components/_card_pick.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_onboarding_card.scss
app/views/bidder/submissions/index.html.erb
app/views/devise/sessions/new.html.erb

changed shadow effect on boxes

changed shadow effect on boxes

---

app/controllers/compatible_responses_controller.rb
app/services/openai_service.rb
app/views/compatible_responses/edit.html.erb
config/routes.rb

score ai is setup

---

app/assets/stylesheets/components/_card_pick.scss

new color added

---

app/assets/stylesheets/components/_card_pick.scss

fixed css bug

---

app/views/bidder/submissions/_submission.html.erb
app/views/bidder/submissions/index.html.erb

bidder submissions tabs made, it's in right order, and I made a parcial for the submissions

bidder submissions tabs index

---

app/controllers/owner/tenders_controller.rb
app/models/tender.rb
app/views/owner/tenders/index.html.erb

added search bar for owner

---

app/assets/stylesheets/components/_card_pick.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_submission.scss
app/views/tenders/_card.html.erb

Owner cards now shows number of submission and color change, orange for 0 submission and green for anything greater.

shows number of submission

---

app/assets/stylesheets/components/_avatar.scss
app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

navbar color change to solid purple

navbar color change to solid purple

---

app/models/compatible_employee.rb
app/models/employee.rb
app/models/user.rb
db/migrate/20250305023937_create_employees.rb
db/migrate/20250305024617_create_compatible_employees.rb
db/schema.rb
test/models/compatible_employee_test.rb
test/models/employee_test.rb

created models for employee and compatible_employee

created models for employee and compatible_employee

---

app/assets/stylesheets/components/_card_pick.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_s-bar.scss
app/views/tenders/index.html.erb

irrelevant changes

---

app/assets/stylesheets/components/_card_pick.scss
app/assets/stylesheets/components/_navbar.scss
app/views/owner/tenders/_draft.html.erb
app/views/tenders/_card.html.erb

working on cards

---

app/assets/stylesheets/components/_card_pick.scss
app/assets/stylesheets/components/_pdf_link.scss
app/views/bidder/submissions/_draft.html.erb
app/views/bidder/submissions/_submission.html.erb
app/views/bidder/submissions/_submission_tab.html.erb

submission pdf upload working

---

app/models/user.rb
app/views/compatible_responses/_show.html.erb
app/views/selected_prerequisites/_team.html.erb
app/views/selected_prerequisites/edit.html.erb
app/views/submissions/show.html.erb
app/views/tenders/_spq_index.html.erb

super page
